name: Run tests

on: [push, pull_request]

jobs:
  test:
    env:
      GHIDRA_INSTALL_DIR: /
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ["10.2"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'coretto'
          java-version: '17'
      - uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 7.3
          arguments: test -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
